version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: webapp
  ignore:
  - dependency-name: vuetify
    versions:
    - 2.4.10
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.0
    - 2.3.1
  - dependency-name: sass
    versions:
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
