<MainScreen>:
    FloatLayout:
        Image:
            source: 'ChampionsOfITKPoster.png'
            size: self.norm_image_size
            pos_hint: {"x":0, "y":0}
        Button:
            font_size: 40
            text_size: self.width, None
            size_hint_y: .2
            size_hint_x: .3
            text: 'Start playing!'
            pos_hint: {"x":.5, "y":.5}
            height: self.texture_size[1]

